version:          "3"
services:
  db:
    image:        mariadb:10.1.39
    volumes:
      - "$PWD/files/mysql_data/:/var/lib/mysql/"
    env_file:     .env
    ports:
      - "3306:3306"
    networks:
      - db-network
  redis:
    image:        redis:alpine
    volumes:
      - "$PWD/files/redis_data/:/data/"
    networks:
      - redis-network
  app:
    image:        k2levin/php-laravel:latest
    volumes:
      - "$PWD/files/index.html:/var/www/html/index.html"
      - "$PWD/laravel/:/var/www/app/laravel/"
      - "$PWD/files/nginx_conf/:/etc/nginx/conf.d/"
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
    networks:
      - redis-network
      - db-network
networks:
  db-network:
  redis-network:
